package libsrc;

public class MText
{
  static final String[] DowNamesCommon;
  static final String[] DowNamesHebrew;
  static final String[][] HolidayNames;
  static final String[] MonthNamesHebrew;
  static final byte[] MonthNamesHebrewShortLength;
  static final String[] MonthNamesSecular;
  static final byte[] MonthNamesSecularShortLength;
  static final String[] SedrotNames;
  static final String[] ShabbathPesachNames;
  static final String[] ShabbathRoshHaShanaNames;
  static final String[] ShabbathTishaBAvNames;
  public static final String TitleErev = "ערב ";
  public static final String[] TitleKatan;
  static final String TitleShabbat = "שבת ";
  public static final String TxtHagDay = ",  יום ";
  public static final String TxtNameDefault = "Default";
  public static final String TxtUnnamed = "Unnamed";
  public static final String[] ZmanimNamesShort;

  static
  {
    String[] arrayOfString1 = new String[14];
    arrayOfString1[0] = "ניסן";
    arrayOfString1[1] = "אייר";
    arrayOfString1[2] = "סיון";
    arrayOfString1[3] = "תמוז";
    arrayOfString1[4] = "אב";
    arrayOfString1[5] = "אלול";
    arrayOfString1[6] = "תשרי";
    arrayOfString1[7] = "חשון";
    arrayOfString1[8] = "כסלו";
    arrayOfString1[9] = "טבת";
    arrayOfString1[10] = "שבט";
    arrayOfString1[11] = "אדר";
    arrayOfString1[12] = "אדר ב'";
    arrayOfString1[13] = "אדר א'";
    MonthNamesHebrew = arrayOfString1;
    byte[] arrayOfByte1 = new byte[14];
    arrayOfByte1[0] = 3;
    arrayOfByte1[2] = 3;
    arrayOfByte1[3] = 3;
    arrayOfByte1[6] = 4;
    arrayOfByte1[7] = 4;
    arrayOfByte1[8] = 3;
    arrayOfByte1[9] = 3;
    arrayOfByte1[10] = 4;
    arrayOfByte1[12] = 18;
    arrayOfByte1[13] = 18;
    MonthNamesHebrewShortLength = arrayOfByte1;
    String[] arrayOfString2 = new String[12];
    arrayOfString2[0] = "ינואר";
    arrayOfString2[1] = "פברואר";
    arrayOfString2[2] = "מרץ";
    arrayOfString2[3] = "אפריל";
    arrayOfString2[4] = "מאי";
    arrayOfString2[5] = "יוני";
    arrayOfString2[6] = "יולי";
    arrayOfString2[7] = "אוגוסט";
    arrayOfString2[8] = "ספטמבר";
    arrayOfString2[9] = "אוקטובר";
    arrayOfString2[10] = "נובמבר";
    arrayOfString2[11] = "דצמבר";
    MonthNamesSecular = arrayOfString2;
    byte[] arrayOfByte2 = new byte[12];
    arrayOfByte2[0] = 3;
    arrayOfByte2[1] = 3;
    arrayOfByte2[2] = 3;
    arrayOfByte2[3] = 3;
    arrayOfByte2[4] = 3;
    arrayOfByte2[5] = 3;
    arrayOfByte2[6] = 3;
    arrayOfByte2[7] = 3;
    arrayOfByte2[8] = 3;
    arrayOfByte2[9] = 3;
    arrayOfByte2[10] = 3;
    arrayOfByte2[11] = 3;
    MonthNamesSecularShortLength = arrayOfByte2;
    String[] arrayOfString3 = new String[7];
    arrayOfString3[0] = "יום ראשון";
    arrayOfString3[1] = "יום שני";
    arrayOfString3[2] = "יום שלישי";
    arrayOfString3[3] = "יום רביעי";
    arrayOfString3[4] = "יום חמישי";
    arrayOfString3[5] = "יום שישי";
    arrayOfString3[6] = "שבת";
    DowNamesCommon = arrayOfString3;
    String[] arrayOfString4 = new String[7];
    arrayOfString4[0] = "יום ראשון";
    arrayOfString4[1] = "יום שני";
    arrayOfString4[2] = "יום שלישי";
    arrayOfString4[3] = "יום רביעי";
    arrayOfString4[4] = "יום חמישי";
    arrayOfString4[5] = "יום שישי";
    arrayOfString4[6] = "שבת";
    DowNamesHebrew = arrayOfString4;
    String[] arrayOfString5 = new String[53];
    arrayOfString5[0] = "בראשית";
    arrayOfString5[1] = "נח";
    arrayOfString5[2] = "לך לך";
    arrayOfString5[3] = "וירא";
    arrayOfString5[4] = "חיי שרה";
    arrayOfString5[5] = "תולדות";
    arrayOfString5[6] = "ויצא";
    arrayOfString5[7] = "וישלח";
    arrayOfString5[8] = "וישב";
    arrayOfString5[9] = "מקץ";
    arrayOfString5[10] = "ויגש";
    arrayOfString5[11] = "ויחי";
    arrayOfString5[12] = "שמות";
    arrayOfString5[13] = "וארא";
    arrayOfString5[14] = "בא";
    arrayOfString5[15] = "בשלח";
    arrayOfString5[16] = "יתרו";
    arrayOfString5[17] = "משפטים";
    arrayOfString5[18] = "תרומה";
    arrayOfString5[19] = "תצוה";
    arrayOfString5[20] = "כי תשא";
    arrayOfString5[21] = "ויקהל";
    arrayOfString5[22] = "פקודי";
    arrayOfString5[23] = "ויקרא";
    arrayOfString5[24] = "צו";
    arrayOfString5[25] = "שמיני";
    arrayOfString5[26] = "תזריע";
    arrayOfString5[27] = "מצורע";
    arrayOfString5[28] = "אחרי מות";
    arrayOfString5[29] = "קדושים";
    arrayOfString5[30] = "אמור";
    arrayOfString5[31] = "בהר";
    arrayOfString5[32] = "בחוקותי";
    arrayOfString5[33] = "במדבר";
    arrayOfString5[34] = "נשא";
    arrayOfString5[35] = "בהעלותך";
    arrayOfString5[36] = "שלח";
    arrayOfString5[37] = "קורח";
    arrayOfString5[38] = "חקת";
    arrayOfString5[39] = "בלק";
    arrayOfString5[40] = "פנחס";
    arrayOfString5[41] = "מטות";
    arrayOfString5[42] = "מסעי";
    arrayOfString5[43] = "דברים";
    arrayOfString5[44] = "ואתחנן";
    arrayOfString5[45] = "עקב";
    arrayOfString5[46] = "ראה";
    arrayOfString5[47] = "שופטים";
    arrayOfString5[48] = "כי תצא";
    arrayOfString5[49] = "כי תבא";
    arrayOfString5[50] = "ניצבים";
    arrayOfString5[51] = "וילך";
    arrayOfString5[52] = "האזינו";
    SedrotNames = arrayOfString5;
    String[][] arrayOfString; = new String[25][];
    String[] arrayOfString6 = new String[2];
    arrayOfString6[0] = "ראש חודש";
    arrayOfString6[1] = "ראש חודש";
    arrayOfString;[0] = arrayOfString6;
    String[] arrayOfString7 = new String[2];
    arrayOfString7[0] = "תענית בכורות";
    arrayOfString7[1] = "תענית בכורות";
    arrayOfString;[1] = arrayOfString7;
    String[] arrayOfString8 = new String[2];
    arrayOfString8[0] = "פסח";
    arrayOfString8[1] = "פסח";
    arrayOfString;[2] = arrayOfString8;
    String[] arrayOfString9 = new String[2];
    arrayOfString9[0] = "יום השואה";
    arrayOfString9[1] = "יום השואה";
    arrayOfString;[3] = arrayOfString9;
    String[] arrayOfString10 = new String[2];
    arrayOfString10[0] = "יום הזיכרון";
    arrayOfString10[1] = "יום הזיכרון";
    arrayOfString;[4] = arrayOfString10;
    String[] arrayOfString11 = new String[2];
    arrayOfString11[0] = "יום העצמאות";
    arrayOfString11[1] = "יום העצמאות";
    arrayOfString;[5] = arrayOfString11;
    String[] arrayOfString12 = new String[2];
    arrayOfString12[0] = "ל\"ג בעומר";
    arrayOfString12[1] = "ל\"ג בעומר";
    arrayOfString;[6] = arrayOfString12;
    String[] arrayOfString13 = new String[2];
    arrayOfString13[0] = "יום ירושלים";
    arrayOfString13[1] = "יום ירושלים";
    arrayOfString;[7] = arrayOfString13;
    String[] arrayOfString14 = new String[2];
    arrayOfString14[0] = "שבועות";
    arrayOfString14[1] = "שבועות";
    arrayOfString;[8] = arrayOfString14;
    String[] arrayOfString15 = new String[2];
    arrayOfString15[0] = "י\"ז בתמוז";
    arrayOfString15[1] = "י\"ז בתמוז";
    arrayOfString;[9] = arrayOfString15;
    String[] arrayOfString16 = new String[2];
    arrayOfString16[0] = "תשעה באב";
    arrayOfString16[1] = "תשעה באב";
    arrayOfString;[10] = arrayOfString16;
    String[] arrayOfString17 = new String[2];
    arrayOfString17[0] = "ט\"ו באב";
    arrayOfString17[1] = "ט\"ו באב";
    arrayOfString;[11] = arrayOfString17;
    String[] arrayOfString18 = new String[2];
    arrayOfString18[0] = "ראש השנה";
    arrayOfString18[1] = "ראש השנה";
    arrayOfString;[12] = arrayOfString18;
    String[] arrayOfString19 = new String[2];
    arrayOfString19[0] = "צום גדליה";
    arrayOfString19[1] = "צום גדליה";
    arrayOfString;[13] = arrayOfString19;
    String[] arrayOfString20 = new String[2];
    arrayOfString20[0] = "יום כיפור";
    arrayOfString20[1] = "יום כיפור";
    arrayOfString;[14] = arrayOfString20;
    String[] arrayOfString21 = new String[2];
    arrayOfString21[0] = "סוכות";
    arrayOfString21[1] = "סוכות";
    arrayOfString;[15] = arrayOfString21;
    String[] arrayOfString22 = new String[2];
    arrayOfString22[0] = "הושענא רבה";
    arrayOfString22[1] = "הושענא רבה";
    arrayOfString;[16] = arrayOfString22;
    String[] arrayOfString23 = new String[2];
    arrayOfString23[0] = "שמיני עצרת";
    arrayOfString23[1] = "שמיני עצרת";
    arrayOfString;[17] = arrayOfString23;
    String[] arrayOfString24 = new String[2];
    arrayOfString24[0] = "שמחת תורה";
    arrayOfString24[1] = "שמחת תורה";
    arrayOfString;[18] = arrayOfString24;
    String[] arrayOfString25 = new String[2];
    arrayOfString25[0] = "חנוכה";
    arrayOfString25[1] = "חנוכה";
    arrayOfString;[19] = arrayOfString25;
    String[] arrayOfString26 = new String[2];
    arrayOfString26[0] = "עשרה בטבת";
    arrayOfString26[1] = "עשרה בטבת";
    arrayOfString;[20] = arrayOfString26;
    String[] arrayOfString27 = new String[2];
    arrayOfString27[0] = "ט\"ו בשבט";
    arrayOfString27[1] = "ט\"ו בשבט";
    arrayOfString;[21] = arrayOfString27;
    String[] arrayOfString28 = new String[2];
    arrayOfString28[0] = "תענית אסתר";
    arrayOfString28[1] = "תענית אסתר";
    arrayOfString;[22] = arrayOfString28;
    String[] arrayOfString29 = new String[2];
    arrayOfString29[0] = "פורים";
    arrayOfString29[1] = "פורים";
    arrayOfString;[23] = arrayOfString29;
    String[] arrayOfString30 = new String[2];
    arrayOfString30[0] = "שושן פורים";
    arrayOfString30[1] = "שושן פורים";
    arrayOfString;[24] = arrayOfString30;
    HolidayNames = arrayOfString;;
    String[] arrayOfString31 = new String[5];
    arrayOfString31[0] = "שקלים";
    arrayOfString31[1] = "זכור";
    arrayOfString31[2] = "פרה";
    arrayOfString31[3] = "החודש";
    arrayOfString31[4] = "הגדול";
    ShabbathPesachNames = arrayOfString31;
    String[] arrayOfString32 = new String[2];
    arrayOfString32[0] = "חזון";
    arrayOfString32[1] = "נחמו";
    ShabbathTishaBAvNames = arrayOfString32;
    String[] arrayOfString33 = new String[1];
    arrayOfString33[0] = "שובה";
    ShabbathRoshHaShanaNames = arrayOfString33;
    String[] arrayOfString34 = new String[2];
    arrayOfString34[0] = " קטן";
    arrayOfString34[1] = " Ktn";
    TitleKatan = arrayOfString34;
    String[] arrayOfString35 = new String[22];
    arrayOfString35[0] = "עלות השחר";
    arrayOfString35[1] = "Early Talit";
    arrayOfString35[2] = "זריחה";
    arrayOfString35[3] = "סזק\"ש מג\"א";
    arrayOfString35[4] = "סזק\"ש גר\"א";
    arrayOfString35[5] = "סזת\"פ מג\"א";
    arrayOfString35[6] = "סזת\"פ גר\"א";
    arrayOfString35[7] = "חצות היום";
    arrayOfString35[8] = "מנחה גדולה";
    arrayOfString35[9] = "MinGdola M A";
    arrayOfString35[10] = "מנחה קטנה";
    arrayOfString35[11] = "MinKtana M A";
    arrayOfString35[12] = "פלג המנחה";
    arrayOfString35[13] = "Plag Min.M A";
    arrayOfString35[14] = "הדלקת נרות";
    arrayOfString35[15] = "שקיעה";
    arrayOfString35[16] = "Dusk Gro";
    arrayOfString35[17] = "צאת הכוכבים גאונים";
    arrayOfString35[18] = "Chazon Ish";
    arrayOfString35[19] = "הבדלה";
    arrayOfString35[20] = "Dusk R\"Taam";
    arrayOfString35[21] = "חצות הליל";
    ZmanimNamesShort = arrayOfString35;
  }

  public static String getDaysText(int paramInt)
  {
    StringBuilder localStringBuilder = new StringBuilder(String.valueOf(String.valueOf(paramInt))).append(" ");
    if (paramInt == 1);
    for (String str = "day"; ; str = "days")
      return str;
  }

  public static String getInNightsText(int paramInt)
  {
    if (paramInt == 1);
    for (String str = "next night"; ; str = "in " + String.valueOf(paramInt) + " nights")
      return str;
  }
}

/* Location:           D:\MySoftware\decomp\classes_dex2jar.jar
 * Qualified Name:     libsrc.MText
 * JD-Core Version:    0.6.0
 */